VALIDATE_ALL_CODEBASE: false
DISABLE:
  - COPYPASTE
  - SPELL
JAVASCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_ES_ARGUMENTS: "--fix --cache"
TYPESCRIPT_ES_CONFIG_FILE: eslint.config.js
TYPESCRIPT_ES_FILE_EXTENSIONS:
  - .ts
  - .tsx
  - .js
  - .jsx
  - .cjs
  - .mjs
JAVASCRIPT_ES_CONFIG_FILE: eslint.config.js
