name: build-bun
on:
  pull_request:
    branches:
    - main
  push:
    branches: 
      - main
      - opt*
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.2.0
      - name: install
        run: |
          rm -f package-lock.json
          bun install -f --trust
      - name: build
        run: |
          bun run --filter "*" build
      - name: ESLint Plus
        uses: bradennapier/eslint-plus-action@v3
        with:
          # GitHub repository token for publishing inline lint annotations. Should be secrets.GITHUB_TOKEN.
          github-token: ${{ github.token }}
          # Use eslintrc?  Defaults to true
          useEslintrc: # optional
          # Set to false to not use eslintignore. Defaults to true
          useEslintIgnore: # optional
          # Run with --fix? Defaults to false
          fix: # optional
          
      - name: test
        run: |
          npm run test --workspaces --if-present
      - name: typecheck
        run: |
          npm run typecheck --workspaces --if-present 
