name: megalinter
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
    

jobs:
  megalinter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run MegaLinter with Ruff
        uses: jgeofil/_mega_linter@38ec200b3e55c11060938da698246e7f1011500d # v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          apply-fixes: 'true'
          apply-fixes-mode: 'commit'
          apply-fixes-event: 'pull_request'

      - name: Upload linting reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: megalinter-reports
          path: megalinter-reports/
